export const enum KEYS {
  C = "C",
  V = "V",
  X = "X",
  Z = "Z",
  Y = "Y",
  A = "A",
  G = "G",
  L = "L",
  F = "F",
  D = "D",
  B = "B",
  P = "P",
  MINUS = "-",
  EQUAL = "=",
  DELETE = "DELETE",
  UP = "ARROWUP",
  DOWN = "ARROWDOWN",
  LEFT = "ARROWLEFT",
  RIGHT = "ARROWRIGHT",
  ENTER = "ENTER",
  SPACE = " ",
  TAB = "TAB",
  BACKSPACE = "BACKSPACE",
  ESC = "ESCAPE",
  PAGEUP = "PAGEUP",
  PAGEDOWN = "PAGEDOWN",
  F5 = "F5",
}

export const HOTKEY_DOC = [
  {
    type: "Universal",
    children: [
      { label: "Cut", value: "Ctrl + X" },
      { label: "Copy", value: "Ctrl + C" },
      { label: "Paste", value: "Ctrl + V" },
      // { label: '快速复制粘贴', value: 'Ctrl + D' },
      { label: "Select all", value: "Ctrl + A" },
      { label: "Undo", value: "Ctrl + Z" },
      { label: "Redo", value: "Ctrl + Y" },
      { label: "Delete", value: "Delete / Backspace" },
      { label: "Multiple choice", value: "Hold Ctrl or Shift" },
      { label: "Print", value: "Ctrl + P" },
      { label: "Close", value: "ESC" },
    ],
  },
  {
    type: "Page preview",
    children: [
      { label: "Preview from first page", value: "F5" },
      { label: "Preview from current page", value: "Shift + F5" },
      { label: "Switch to previous page", value: "↑ / ← / PgUp" },
      { label: "Switch to next page", value: "↓ / → / PgDown" },
      { label: "Switch to next page", value: "Enter / Space" },
      { label: "Exit", value: "ESC" },
    ],
  },
  {
    type: "Page editing",
    children: [
      { label: "Create new page", value: "Enter" },
      { label: "Move", value: "Space + mouse drag" },
      { label: "Zoom", value: "Ctrl + mouse wheel" },
      { label: "Enlarge", value: "Ctrl + =" },
      { label: "Reduce", value: "Ctrl + -" },
      { label: "Adapt to screen", value: "Ctrl + 0" },
      { label: "Previous page (unselected element)", value: "↑ / ←" },
      { label: "Next page (unselected element)", value: "↓ / →" },
      { label: "Previous page", value: "Mouse scroll up/PgUp" },
      { label: "Next page", value: "Mouse scroll down/PgDown" },
    ],
  },
  {
    type: "Element operations",
    children: [
      { label: "Move", value: "↑ / ← / ↓ / →" },
      { label: "Lock", value: "Ctrl + L" },
      { label: "Group", value: "Ctrl + G" },
      { label: "Ungroup", value: "Ctrl + Shift + G" },
      { label: "Put on top", value: "Alt + F" },
      { label: "Place on the ground floor", value: "Alt + B" },
      { label: "Lock aspect ratio", value: "Hold Ctrl or Shift" },
      {
        label: "Create horizontal/vertical lines",
        value: "Hold Ctrl or Shift",
      },
      { label: "Switch focus element", value: "Tab" },
      { label: "Confirm picture cropping", value: "Enter" },
    ],
  },
  {
    type: "Table editing",
    children: [
      { label: "Focus on next cell", value: "Tab" },
      { label: "Insert a row above", value: "Ctrl + ↑" },
      { label: "Insert a line below", value: "Ctrl + ↓" },
      { label: "Insert a column on the left", value: "Ctrl + ←" },
      { label: "Insert a column on the right", value: "Ctrl + →" },
    ],
  },
  // {
  //   type: '图表数据编辑',
  //   children: [
  //     { label: '聚焦到下一行', value: 'Enter' },
  //   ],
  // },
  {
    type: "Text Editor",
    children: [
      { label: "Bold", value: "Ctrl + B" },
      { label: "Italic", value: "Ctrl + I" },
      { label: "Underline", value: "Ctrl + U" },
      { label: "Strikethrough", value: "Ctrl + D" },
    ],
  },
];
